# $HOME/.bashrc
#
# this file is sourced by all *interactive* bash shells on startup,
# including some apparently interactive shells such as scp and rcp
# that can't tolerate any output. so make sure this doesn't display
# anything or bad things will happen !

# test for an interactive shell. there is no need to set anything
# past this point for scp and rcp, and it's important to refrain from
# outputting anything in those cases.
if [[ $- != *i* ]] ; then
  # shell is non-interactive. be done now!
  return
fi

# load all files from .shell/bashrc.d directory
if [ -d $HOME/.shellrc/bashrc.d ]; then
  for file in $HOME/.shellrc/bashrc.d/*.bash; do
    [ -e "$file" ] && source $file
  done
fi

# load all files from .shell/bashrc.d.osx directory
if [[ "$(uname)" == "Darwin" ]]; then
  if [ -d $HOME/.shellrc/bashrc.d.osx ]; then
    for file in $HOME/.shellrc/bashrc.d.osx/*.bash; do
      [ -e "$file" ] && source $file
    done
  fi
fi

# load all files from .shell/rc.d directory
if [ -d $HOME/.shellrc/rc.d ]; then
  for file in $HOME/.shellrc/rc.d/*.sh; do
    [ -e "$file" ] && source $file
  done
fi

# load all files from .shell/rc.d.osx directory
if [[ "$(uname)" == "Darwin" ]]; then
  if [ -d $HOME/.shellrc/rc.d.osx ]; then
    for file in $HOME/.shellrc/rc.d.osx/*.sh; do
      [ -e "$file" ] && source $file
    done
  fi
fi
