if [ -f $HOME/.bashrc ]; then
  source $HOME/.bashrc
fi

# load all files from .shell/login.d directory
if [ -d $HOME/.shellrc/login.d ]; then
  for file in $HOME/.shellrc/login.d/*.sh; do
    [ -e "$file" ] && source $file
  done
fi

# load all files from .shell/login.d directory
if [[ "$(uname)" == "Darwin" ]]; then
  if [ -d $HOME/.shellrc/login.d.osx ]; then
    for file in $HOME/.shellrc/login.d.osx/*.sh; do
      [ -e "$file" ] && source $file
    done
  fi
fi

# >>> JVM installed by coursier >>>
export JAVA_HOME="/Users/rball/Library/Caches/Coursier/arc/https/github.com/AdoptOpenJDK/openjdk8-binaries/releases/download/jdk8u292-b10/OpenJDK8U-jdk_x64_mac_hotspot_8u292b10.tar.gz/jdk8u292-b10/Contents/Home"
# <<< JVM installed by coursier <<<

# >>> coursier install directory >>>
export PATH="$PATH:/Users/rball/Library/Application Support/Coursier/bin"
# <<< coursier install directory <<<

source /Users/rball/.docker/init-bash.sh || true # Added by Docker Desktop
